// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EstudenCRUD.Models
{
    public partial class Estudents
    {
        public int IdStudent { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
    }
}